### ISSUE TITLE
grgit-core as runtime dependency for grgit-gradle from gradle plugin portal

### ISSUE THREAD

**Issue by artemy-osipov** [ajoberstar/grgit#271]
grgit-core has not resolved in compileClasspath for grgit-gradle from gradle plugin portal when using Gradle 5.0

build.gradle:
```
plugins {
    id 'groovy'
}

repositories {
    gradlePluginPortal()
}

dependencies {
    compile 'org.ajoberstar.grgit:grgit-gradle:3.0.0'
    compile 'org.codehaus.groovy:groovy-all:2.5.0'
}
```

result of ./gradlew dependencies --configuration compileClasspath
```
compileClasspath - Compile classpath for source set 'main'.
+--- org.ajoberstar.grgit:grgit-gradle:3.0.0
\--- org.codehaus.groovy:groovy-all:2.5.0
     +--- org.codehaus.groovy:groovy:2.5.0
...
```

But grgit-gradle from jcenter works well
```
compileClasspath - Compile classpath for source set 'main'.
+--- org.ajoberstar.grgit:grgit-gradle:3.0.0
|    \--- org.ajoberstar.grgit:grgit-core:3.0.0
|         \--- org.eclipse.jgit:org.eclipse.jgit:5.1.3.201810200350-r
|              +--- com.jcraft:jsch:0.1.54
|              +--- com.jcraft:jzlib:1.1.1
|              +--- com.googlecode.javaewah:JavaEWAH:1.1.6
|              \--- org.slf4j:slf4j-api:1.7.2
\--- org.codehaus.groovy:groovy-all:2.5.0
     +--- org.codehaus.groovy:groovy:2.5.0
...
```

Probably that happens via different dependency block in their pom
* [plugin portal](https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-gradle/3.0.0/)
* [jcenter](https://bintray.com/beta/#/ajoberstar/maven/grgit/3.0.0?tab=files)

**Comment by jjohannes** [comment]
Hi. Unfortunately, this is still (or again) an issue with **4.1.1** (tested with Gradle 7.3.1).

If you [look at the POM](https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-gradle/4.1.1/grgit-gradle-4.1.1.pom), you notice that there are two entries for `grgit-core`:

```
    <dependency>
      <groupId>org.ajoberstar.grgit</groupId>
      <artifactId>grgit-core</artifactId>
      <version>4.1.1</version>
      <scope>compile</scope>
      <type>jar</type>
      <optional>false</optional>
    </dependency>
    <dependency>
      <groupId>org.ajoberstar.grgit</groupId>
      <artifactId>grgit-core</artifactId>
      <version>4.1.1</version>
      <scope>runtime</scope>
      <type>jar</type>
      <optional>false</optional>
    </dependency>
```

Looks like Gradle uses the last one if there are multiple entires. You could argue that Gradle could be a bit more "careful" when parsing the POM, but having these two entries also does not make much sense. Usually, there should be only one entry for each dependency. And `compile` scope in Maven already means that it is included at `runtime`. Hence, the second entry can be removed. I don't know how it ends up in there though.

**Comment by ajoberstar** [comment]
Resolved in 5.0.0

**Comment by jjohannes** [comment]
Thanks for having a look at this @ajoberstar. Unfortunately, the issue is still present [in the 5.0.0-rc.3.pom](https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-gradle/5.0.0-rc.3/grgit-gradle-5.0.0-rc.3.pom).

**Comment by jjohannes** [comment]
My bad, I missed

> As of 5.0.0, this project is no longer directly published to the Gradle Plugin Portal

and thought `rc.3` was the latest. Works well with `rc.7`. :+1: Thanks for fixing!
